# Generated by Django 4.2 on 2025-07-08 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_pemilihan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kandidat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visi', models.TextField()),
                ('misi', models.TextField()),
                ('proker', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='kandidat/images/')),
                ('ketua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandidat_ketua', to=settings.AUTH_USER_MODEL)),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kandidat_list', to='main.pemilihan')),
                ('wakil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kandidat_wakil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('pemilihan', 'ketua', 'wakil')},
            },
        ),
    ]
