# Generated by Django 4.2 on 2025-07-08 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_kandidat'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='kandidat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='kandidat',
            name='nomor_urut',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pemilihan',
            name='pemilih',
            field=models.ManyToManyField(blank=True, related_name='pemilihan_diikuti', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='kandidat/'),
        ),
        migrations.AlterField(
            model_name='pemilihan',
            name='deskripsi',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pemilihan',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
