# Generated by Django 4.2 on 2025-07-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_kandidat_nomor_urut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='nomor_urut',
            field=models.PositiveIntegerField(),
        ),
    ]
