# Generated by Django 4.2 on 2025-07-10 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_kandidat_nomor_urut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kandidat',
            name='foto',
            field=models.ImageField(blank=True, default='kandidat/default.png', null=True, upload_to='kandidat/'),
        ),
        migrations.AlterUniqueTogether(
            name='kandidat',
            unique_together={('pemilihan', 'nomor_urut')},
        ),
        migrations.CreateModel(
            name='Suara',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu', models.DateTimeField(auto_now_add=True)),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_kandidat', to='main.kandidat')),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_user', to=settings.AUTH_USER_MODEL)),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suara_list', to='main.pemilihan')),
            ],
            options={
                'unique_together': {('pemilihan', 'pemilih')},
            },
        ),
    ]
