# Generated by Django 4.2 on 2025-07-10 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_kandidat_foto_alter_kandidat_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('digunakan', models.BooleanField(default=False)),
                ('waktu_dibuat', models.DateTimeField(auto_now_add=True)),
                ('waktu_digunakan', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField()),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilihan')),
            ],
            options={
                'unique_together': {('pemilihan', 'pemilih')},
            },
        ),
    ]
