# Generated by Django 4.2 on 2025-07-11 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_tokenvote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenvote',
            name='token',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
