# Generated by Django 4.2 on 2025-07-12 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_tokenvote_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogVotingActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waktu_vote', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('pemilih', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('pemilihan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pemilihan')),
            ],
        ),
    ]
