# Generated by Django 4.2 on 2025-07-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_suara_ip_address_suara_user_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='suara',
            name='is_suspicious',
            field=models.BooleanField(default=False),
        ),
    ]
