# Generated by Django 4.2 on 2025-07-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_suara_is_suspicious'),
    ]

    operations = [
        migrations.AddField(
            model_name='suara',
            name='alasan_kecurangan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
