# Generated by Django 4.2 on 2025-07-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_suara_alasan_kecurangan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogVotingActivity',
        ),
    ]
